# fly.toml file generated for hidewallbot on 2022-03-18T23:36:32+01:00

app = "hidewallbot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  strategy = "immediate"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"
